<?php
/**
 * Plugin Name:       stock sync woocommerce
 * Plugin URI:        https://iwebxstudio.com/
 * Description:       ซิงค์สินค้าและสต็อก จากระบบภายนอก เข้า WooCommerce อัตโนมัติ ผ่านการเชื่อมต่อ API และ Cron Job ทำงาน 24/7
 * Version:           1.0.0
 * Author:            iwebxstudio
 * Author URI:        https://iwebxstudio.com/
 * Text Domain:       ssw
 * Domain Path:       /languages
 *
 * Generated by WordPress Plugin Generator v1.1.1 (wordpressplugingenerator.com)
 *
 */

// Prevent to access the file from outside of WordPress
if (!defined('ABSPATH')) exit;

define('SSW_VERSION', '1.0.0');
define('SSW_PLUGIN_DIR', plugin_dir_path(__FILE__));
define('SSW_PLUGIN_URL', plugin_dir_url(__FILE__));

// Load all required classes
require_once SSW_PLUGIN_DIR . 'includes/class-logger.php';
require_once SSW_PLUGIN_DIR . 'includes/class-api-client.php';
require_once SSW_PLUGIN_DIR . 'includes/class-product-sync.php';
require_once SSW_PLUGIN_DIR . 'includes/class-cron-manager.php';
require_once SSW_PLUGIN_DIR . 'includes/class-admin.php';

// Check WooCommerce active and initialize
add_action('plugins_loaded', function() {
    if (!class_exists('WooCommerce')) {
        add_action('admin_notices', function() {
            echo '<div class="error"><p>' . esc_html__('WooCommerce is required for Stock Sync plugin to work!', 'ssw') . '</p></div>';
        });
        return;
    }
    
    // Initialize Plugin
    new SSW_Cron_Manager();
    new SSW_Admin();
});

// Register activation hook
register_activation_hook(__FILE__, function() {
    $cron = new SSW_Cron_Manager();
    $cron->activate();
});

// Register deactivation hook
register_deactivation_hook(__FILE__, function() {
    $cron = new SSW_Cron_Manager();
    $cron->deactivate();
});